name: Node.js CI

on:
  push:
    branches: [ main, dev ]
    paths-ignore:
        - 'LICENSE'
        - 'README.md'
  pull_request:
    branches: [ dev ]
    paths-ignore:
        - 'LICENSE'
        - 'README.md'

jobs:
  test:

    env:
      MONGO_TEST_URL: ${{ secrets.MONGO_TEST_URL }}

    strategy:
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run lint
    - run: npm run mocha test/tools.js
    - run: npm run mocha test/site-mongoless.js
    - run: npm run mocha test/site-auth.js
